import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class AppLanguage {
  final String code;
  final String name;
  final String flag;
  const AppLanguage({required this.code, required this.name, required this.flag});
}

class LocalizationService {
  static const _keyLanguage = 'selected_language';
  static final ValueNotifier<Locale> currentLocale = ValueNotifier(const Locale('id'));

  static const List<AppLanguage> allSupportedLanguages = [
    AppLanguage(code: 'id', name: 'Bahasa Indonesia', flag: '🇮🇩'),
    AppLanguage(code: 'en', name: 'English', flag: '🇬🇧'),
    AppLanguage(code: 'su', name: 'Basa Sunda', flag: '🇸🇩'),
    AppLanguage(code: 'jv', name: 'Basa Jawa', flag: '🇮🇩'),
    AppLanguage(code: 'ar', name: 'العربية (Arabic)', flag: '🇸🇦'),
    AppLanguage(code: 'ja', name: '日本語 (Japanese)', flag: '🇯🇵'),
  ];

  static const Map<String, Map<String, String>> _localizedValues = {
    'id': {
      'app_title': 'OSIS Management',
      'app_subtitle': 'Sistem Manajemen OSIS Digital',
      'login_as': 'Login sebagai:',
      'nav_proker': 'Proker',
      'nav_laporan': 'Laporan',
      'nav_arsip': 'Arsip',
      'nav_pelanggaran': 'Pelanggaran',
      'nav_rekap': 'Rekap',
      'nav_manajemen': 'Manajemen',
      'nav_admin': 'Admin Panel',
      'nav_settings': 'Pengaturan',
      'btn_login': 'Masuk',
      'btn_logout': 'Logout',
      'btn_save': 'Simpan',
      'btn_cancel': 'Batal',
      'btn_delete': 'Hapus',
      'btn_edit': 'Edit',
      'btn_add': 'Tambah',
      'btn_search': 'Cari...',
      'btn_refresh': 'Segarkan',
      'btn_close': 'Tutup',
      'btn_reset': 'Reset',
      'btn_apply': 'Terapkan',
      'settings_title': 'Pengaturan & Preferensi',
      'theme_mode': 'Mode Tampilan',
      'theme_light': 'White (Light) Mode',
      'theme_dark': 'Dark Mode',
      'theme_system': 'Ikuti Sistem',
      'theme_color': 'Warna Aksen Tema',
      'language': 'Bahasa Aplikasi',
      'language_id': 'Bahasa Indonesia',
      'language_en': 'English',
      'change_password': 'Ganti Password Akun',
      'admin_config': 'Konfigurasi Sistem (Admin)',
      'about_app': 'Tentang Aplikasi',
      'notifications': 'Pusat Notifikasi',
      'cloud_status': 'Status Koneksi Cloud',
      'username': 'Username',
      'password': 'Password',
      'new_password': 'Password Baru',
      'confirm_logout': 'Konfirmasi Logout',
      'logout_prompt': 'Apakah Anda yakin ingin keluar?',
      'role_admin': 'Super Admin Sistem',
      'role_pembina': 'Pembina OSIS',
      'role_kesiswaan': 'Staf Kesiswaan',
      'role_ketua': 'Ketua OSIS',
      'role_wakil': 'Wakil Ketua OSIS',
      'role_sekretaris': 'Sekretaris OSIS',
      'role_bendahara': 'Bendahara OSIS',
      'msg_saved': 'Perubahan berhasil disimpan',
      'msg_deleted': 'Data berhasil dihapus',
      'msg_error': 'Terjadi kesalahan',
      'msg_sync_success': 'Sinkronisasi berhasil',
    },
    'en': {
      'app_title': 'OSIS Management',
      'app_subtitle': 'Digital OSIS Management System',
      'login_as': 'Logged in as:',
      'nav_proker': 'Work Plan',
      'nav_laporan': 'Reports',
      'nav_arsip': 'Archive',
      'nav_pelanggaran': 'Discipline',
      'nav_rekap': 'Recap',
      'nav_manajemen': 'Management',
      'nav_admin': 'Admin Panel',
      'nav_settings': 'Settings',
      'btn_login': 'Sign In',
      'btn_logout': 'Sign Out',
      'btn_save': 'Save',
      'btn_cancel': 'Cancel',
      'btn_delete': 'Delete',
      'btn_edit': 'Edit',
      'btn_add': 'Add',
      'btn_search': 'Search...',
      'btn_refresh': 'Refresh',
      'btn_close': 'Close',
      'btn_reset': 'Reset',
      'btn_apply': 'Apply',
      'settings_title': 'Settings & Preferences',
      'theme_mode': 'Display Mode',
      'theme_light': 'White (Light) Mode',
      'theme_dark': 'Dark Mode',
      'theme_system': 'System Default',
      'theme_color': 'Theme Accent Color',
      'language': 'App Language',
      'language_id': 'Indonesian (Bahasa Indonesia)',
      'language_en': 'English',
      'change_password': 'Change Account Password',
      'admin_config': 'System Configuration (Admin)',
      'about_app': 'About App',
      'notifications': 'Notification Center',
      'cloud_status': 'Cloud Connection Status',
      'username': 'Username',
      'password': 'Password',
      'new_password': 'New Password',
      'confirm_logout': 'Confirm Sign Out',
      'logout_prompt': 'Are you sure you want to sign out?',
      'role_admin': 'Super System Admin',
      'role_pembina': 'OSIS Supervisor (Pembina)',
      'role_kesiswaan': 'Student Affairs Staff (Kesiswaan)',
      'role_ketua': 'OSIS President (Ketua)',
      'role_wakil': 'OSIS Vice President (Wakil)',
      'role_sekretaris': 'OSIS Secretary (Sekretaris)',
      'role_bendahara': 'OSIS Treasurer (Bendahara)',
      'msg_saved': 'Changes saved successfully',
      'msg_deleted': 'Data deleted successfully',
      'msg_error': 'An error occurred',
      'msg_sync_success': 'Synchronization successful',
    },
    'su': {
      'app_title': 'Manajemen OSIS',
      'app_subtitle': 'Sistem Pangaturan OSIS Digital',
      'login_as': 'Asup salaku:',
      'nav_proker': 'Proker',
      'nav_laporan': 'Laporan',
      'nav_arsip': 'Arsip',
      'nav_pelanggaran': 'Pelanggaran',
      'nav_rekap': 'Rekap',
      'nav_manajemen': 'Manajemen',
      'nav_admin': 'Panel Admin',
      'nav_settings': 'Setelan',
      'btn_login': 'Asup',
      'btn_logout': 'Kaluar',
      'btn_save': 'Simpen',
      'btn_cancel': 'Batal',
      'btn_delete': 'Hapus',
      'btn_edit': 'Robi',
      'btn_add': 'Tambah',
      'btn_search': 'Pilari...',
      'btn_refresh': 'Segerkeun',
      'btn_close': 'Tutup',
      'btn_reset': 'Reset',
      'btn_apply': 'Larapkeun',
      'settings_title': 'Setelan & Pilihan',
      'theme_mode': 'Mode Tampilan',
      'theme_light': 'Mode Caang (Light)',
      'theme_dark': 'Mode Poek (Dark)',
      'theme_system': 'Nurutkeun Sistem',
      'theme_color': 'Warna Tema',
      'language': 'Basa Aplikasi',
      'language_id': 'Basa Indonesia',
      'language_en': 'Basa Inggris',
      'change_password': 'Ganti Sandi Akun',
      'admin_config': 'Konfigurasi Admin',
      'about_app': 'Ngeunaan Aplikasi',
      'notifications': 'Bewara Notifikasi',
      'cloud_status': 'Status Sambungan Cloud',
      'username': 'Nami Pamake',
      'password': 'Kecap Sandi',
      'new_password': 'Kecap Sandi Anyar',
      'confirm_logout': 'Konfirmasi Kaluar',
      'logout_prompt': 'Naha anjeun yakin hoyong kaluar?',
      'role_admin': 'Super Admin Sistem',
      'role_pembina': 'Pembina OSIS',
      'role_kesiswaan': 'Staf Kesiswaan',
      'role_ketua': 'Pupuhu OSIS',
      'role_wakil': 'Wakil Pupuhu OSIS',
      'role_sekretaris': 'Sekretaris OSIS',
      'role_bendahara': 'Bendahara OSIS',
      'msg_saved': 'Parobahan parantos disimpen',
      'msg_deleted': 'Data parantos dihapus',
      'msg_error': 'Aya kasalahan',
      'msg_sync_success': 'Singkronisasi hasil',
    },
    'jv': {
      'app_title': 'Manajemen OSIS',
      'app_subtitle': 'Sistem Manajemen OSIS Digital',
      'login_as': 'Mlebu minangka:',
      'nav_proker': 'Proker',
      'nav_laporan': 'Laporan',
      'nav_arsip': 'Arsip',
      'nav_pelanggaran': 'Pelanggaran',
      'nav_rekap': 'Rekap',
      'nav_manajemen': 'Manajemen',
      'nav_admin': 'Panel Admin',
      'nav_settings': 'Setelan',
      'btn_login': 'Mlebu',
      'btn_logout': 'Metu',
      'btn_save': 'Simpen',
      'btn_cancel': 'Batal',
      'btn_delete': 'Busak',
      'btn_edit': 'Owahi',
      'btn_add': 'Tambah',
      'btn_search': 'Goleki...',
      'btn_refresh': 'Anyari',
      'btn_close': 'Tutup',
      'btn_reset': 'Reset',
      'btn_apply': 'Terapke',
      'settings_title': 'Setelan & Pilihan',
      'theme_mode': 'Mode Tampilan',
      'theme_light': 'Mode Padhang (Light)',
      'theme_dark': 'Mode Peteng (Dark)',
      'theme_system': 'Melu Sistem',
      'theme_color': 'Werna Tema',
      'language': 'Basa Aplikasi',
      'language_id': 'Basa Indonesia',
      'language_en': 'Basa Inggris',
      'change_password': 'Ganti Sandi Akun',
      'admin_config': 'Konfigurasi Admin',
      'about_app': 'Babagan Aplikasi',
      'notifications': 'Pusat Notifikasi',
      'cloud_status': 'Status Sambungan Cloud',
      'username': 'Jeneng Penganggo',
      'password': 'Tembung Sandi',
      'new_password': 'Tembung Sandi Anyar',
      'confirm_logout': 'Konfirmasi Metu',
      'logout_prompt': 'Apa sampeyan yakin arep metu?',
      'role_admin': 'Super Admin Sistem',
      'role_pembina': 'Pembina OSIS',
      'role_kesiswaan': 'Staf Kesiswaan',
      'role_ketua': 'Ketua OSIS',
      'role_wakil': 'Wakil Ketua OSIS',
      'role_sekretaris': 'Sekretaris OSIS',
      'role_bendahara': 'Bendahara OSIS',
      'msg_saved': 'Owah-owahan kasil disimpen',
      'msg_deleted': 'Data kasil dibusak',
      'msg_error': 'Ana kaluputan',
      'msg_sync_success': 'Sinkronisasi kasil',
    },
    'ar': {
      'app_title': 'إدارة اتحاد الطلاب',
      'app_subtitle': 'النظام الرقمي لإدارة الأنشطة الطلابية',
      'login_as': 'مسجل باسم:',
      'nav_proker': 'خطة العمل',
      'nav_laporan': 'التقارير',
      'nav_arsip': 'الأرشيف',
      'nav_pelanggaran': 'المخالفات',
      'nav_rekap': 'الإحصائيات',
      'nav_manajemen': 'الإدارة',
      'nav_admin': 'لوحة الإدارة',
      'nav_settings': 'الإعدادات',
      'btn_login': 'تسجيل الدخول',
      'btn_logout': 'تسجيل الخروج',
      'btn_save': 'حفظ',
      'btn_cancel': 'إلغاء',
      'btn_delete': 'حذف',
      'btn_edit': 'تعديل',
      'btn_add': 'إضافة',
      'btn_search': 'بحث...',
      'btn_refresh': 'تحديث',
      'btn_close': 'إغلاق',
      'btn_reset': 'إعادة تعيين',
      'btn_apply': 'تطبيق',
      'settings_title': 'الإعدادات والتفضيلات',
      'theme_mode': 'وضع العرض',
      'theme_light': 'الوضع المضيء',
      'theme_dark': 'الوضع الليلي',
      'theme_system': 'حسب النظام',
      'theme_color': 'لون السمة',
      'language': 'لغة التطبيق',
      'language_id': 'الإندونيسية',
      'language_en': 'الإنجليزية',
      'change_password': 'تغيير كلمة المرور',
      'admin_config': 'إعدادات المشرف',
      'about_app': 'عن التطبيق',
      'notifications': 'مركز الإشعارات',
      'cloud_status': 'حالة السحابة',
      'username': 'اسم المستخدم',
      'password': 'كلمة المرور',
      'new_password': 'كلمة المرور الجديدة',
      'confirm_logout': 'تأكيد الخروج',
      'logout_prompt': 'هل أنت متأكد من تسجيل الخروج؟',
      'role_admin': 'المشرف الرئيسي',
      'role_pembina': 'المشرف التربوي',
      'role_kesiswaan': 'شؤون الطلاب',
      'role_ketua': 'رئيس الاتحاد',
      'role_wakil': 'نائب الرئيس',
      'role_sekretaris': 'أمين السر',
      'role_bendahara': 'أمين الصندوق',
      'msg_saved': 'تم حفظ التغييرات بنجاح',
      'msg_deleted': 'تم حذف البيانات بنجاح',
      'msg_error': 'حدث خطأ',
      'msg_sync_success': 'تمت المزامنة بنجاح',
    },
    'ja': {
      'app_title': '生徒会管理システム',
      'app_subtitle': 'デジタル生徒会管理プラットフォーム',
      'login_as': 'ログイン中:',
      'nav_proker': '活動計画',
      'nav_laporan': '報告書',
      'nav_arsip': 'アーカイブ',
      'nav_pelanggaran': '規律管理',
      'nav_rekap': '集計データ',
      'nav_manajemen': 'システム管理',
      'nav_admin': '管理者パネル',
      'nav_settings': '設定',
      'btn_login': 'ログイン',
      'btn_logout': 'ログアウト',
      'btn_save': '保存',
      'btn_cancel': 'キャンセル',
      'btn_delete': '削除',
      'btn_edit': '編集',
      'btn_add': '追加',
      'btn_search': '検索...',
      'btn_refresh': '更新',
      'btn_close': '閉じる',
      'btn_reset': 'リセット',
      'btn_apply': '適用',
      'settings_title': '設定と環境設定',
      'theme_mode': 'テーマモード',
      'theme_light': 'ライトモード',
      'theme_dark': 'ダークモード',
      'theme_system': 'システム連動',
      'theme_color': 'アクセントカラー',
      'language': 'アプリ言語',
      'language_id': 'インドネシア語',
      'language_en': '英語',
      'change_password': 'パスワード変更',
      'admin_config': 'システム設定（管理者）',
      'about_app': 'アプリについて',
      'notifications': '通知センター',
      'cloud_status': 'クラウド状態',
      'username': 'ユーザー名',
      'password': 'パスワード',
      'new_password': '新しいパスワード',
      'confirm_logout': 'ログアウトの確認',
      'logout_prompt': '本当にログアウトしますか？',
      'role_admin': 'システム管理者',
      'role_pembina': '顧問・指導教員',
      'role_kesiswaan': '生徒指導部',
      'role_ketua': '生徒会長',
      'role_wakil': '副生徒会長',
      'role_sekretaris': '書記',
      'role_bendahara': '会計',
      'msg_saved': '変更が正常に保存されました',
      'msg_deleted': 'データを正常に削除しました',
      'msg_error': 'エラーが発生しました',
      'msg_sync_success': '同期に成功しました',
    },
  };

  static Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    final langCode = prefs.getString(_keyLanguage) ?? 'id';
    currentLocale.value = Locale(_localizedValues.containsKey(langCode) ? langCode : 'id');
  }

  static Future<void> setLanguage(String langCode) async {
    final code = _localizedValues.containsKey(langCode) ? langCode : 'id';
    currentLocale.value = Locale(code);
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_keyLanguage, code);
  }

  static String tr(String key) {
    final code = currentLocale.value.languageCode;
    return _localizedValues[code]?[key] ?? _localizedValues['id']?[key] ?? key;
  }
}

extension AppLocalizationExtension on BuildContext {
  String tr(String key) => LocalizationService.tr(key);
}
